---
title: "Scatterplots"
output:
  word_document: default
  html_document: default
---

```{r}
library(ggplot2)
library(dplyr)
```



```{r setup, include=FALSE}
pf <- read.csv('pseudo_facebook.tsv', sep= '\t')
```

```{r}
summary(pf$age)
```


```{r}
#qplot(age, friend_count, data=pf)
#The age variable becomes discrete so we use alpha 1/20 so we can have depth and understand the numbers
ggplot(aes(x=age, y=friend_count, color='blue'), data=pf) + 
  geom_jitter(alpha = 1/20) +
  xlim(13,90)
```


```{r}
#Note we need to make sure the minimum height of the jitter to be 0 because we're using sqrt
ggplot(aes(x=age, y=friend_count, color='blue'), data=pf) + 
  geom_jitter(alpha = 1/20, position=position_jitter(h = 0)) +
  xlim(13,90)+
  coord_trans(y="sqrt")
```


```{r}
ggplot(aes(x=age, y=friendships_initiated, color='blue'), data=pf)+
  geom_jitter(alpha = 1/10, position = position_jitter(h = 0))+
  coord_trans(y='sqrt')
```



```{r}
#Arranging by age group. The %>% chains the function to the pf dataset
pf.fc_by_age <- pf %>%
  group_by(age) %>%
  summarise(friend_count_mean = mean(friend_count),
            friend_count_median = median(friend_count),
            n = n()) %>%
  arrange(age)
```


```{r}
#Plotting the median friend count
ggplot(aes(x=age, y=friend_count_mean), data = pf.fc_by_age)+
  geom_point(color = 'blue') + geom_line()
```



```{r}
ggplot(aes(x=age, y=friendships_initiated), data=pf)+
  xlim(13,90) +
  geom_jitter(alpha = 0.05, 
              position = position_jitter(h = 0),
              color = 'orange') +
  coord_trans(y='sqrt')+
  geom_line(stat = 'summary', fun.y=mean)
```



```{r}
#Below we added the have the 90% and 10% quantiles (dotted blue lines)
#The mean is the black line
#The median is the solid blue line
ggplot(aes(x=age, y=friendships_initiated), data=pf)+
  xlim(13,90) +
  geom_jitter(alpha = 0.05, 
              position = position_jitter(h = 0),
              color = 'orange') +
  coord_trans(y='sqrt')+
  geom_line(stat = 'summary', fun.y=mean) +
  geom_line(stat = 'summary', fun.y=quantile, fun.args = list(probs = .1), linetype = 2, color = 'blue')+
  geom_line(stat = 'summary', fun.y=quantile, fun.args = list(probs = .5), color = 'blue')+
  geom_line(stat = 'summary', fun.y=quantile, fun.args = list(probs = .9), linetype = 2, color = 'blue')
```



```{r}
#Using coord_cartesian to zoom in to 600 and below
ggplot(aes(x=age, y=friendships_initiated), data=pf)+
  geom_point(alpha = 0.05, 
              position = position_jitter(h = 0),
              color = 'orange') +
  coord_cartesian(xlim = c(13,70), ylim = c(0,1000))+
  geom_line(stat = 'summary', fun.y=mean) +
  geom_line(stat = 'summary', fun.y=quantile, fun.args = list(probs = .1),
            linetype = 2, color = 'blue')+
  geom_line(stat = 'summary', fun.y=quantile, fun.args = list(probs = .5),
            color = 'blue')+
  geom_line(stat = 'summary', fun.y=quantile, fun.args = list(probs = .9),
            linetype = 2, color = 'blue')
```


```{r}
#Calculating the correlation coefficient betweenage count and friend count 0.3 = meaningful but small
#No real correlation
with(pf, cor.test(age, friend_count, method='pearson'))
```

```{r}
#When we subset the data for users 70 and younger we can see negative correlation
with(subset(pf, age<=70), cor.test(age, friend_count))
```

```{r}
ggplot(pf, aes(x=www_likes_received, y=likes_received))+geom_point(alpha=0.05, color = 'blue')+
  xlim(0, quantile(pf$www_likes_received, 0.95))+
  ylim(0, quantile(pf$likes_received, 0.95))+
  geom_smooth(method = 'lm', color = 'red')
```


```{r}
with(pf, cor.test(www_likes_received, likes_received))
```


```{r}
#Adding a category that also factors in months to the age
pf$age_with_months <- with(pf, age + (12 - dob_month)/12)
```

```{r}
library(dplyr)
pf.fc_by_age_months <- pf %>%
  group_by(age_with_months) %>%
  summarise(friend_count_mean = mean(friend_count),
            friend_count_median = median(friend_count),
            n = n()) %>%
  arrange(age_with_months)

head(pf.fc_by_age_months)
```


```{r}
ggplot(aes(x=age, y=friend_count_mean), data = subset(pf.fc_by_age, age < 71))+
  geom_line()
```



```{r}
#plotting the 71 or less age with months
#plotting the age without months, and then plotting the average so its a smooth rolling chart of 5yr averages
#Note we want the average friend count so we add a stat applying the mean function to the line

p1 <- ggplot(subset(pf.fc_by_age_months, age_with_months < 71), aes(x=age_with_months, y=friend_count_mean))+            geom_line()+
  geom_smooth()

p2 <- ggplot(aes(x=age, y=friend_count_mean), data = subset(pf.fc_by_age, age < 71))+
  geom_line()+
  geom_smooth()

p3 <- ggplot(subset(pf, age<71), aes(x=round(age/5)*5, y=friend_count)) +
  geom_line(stat = 'summary', fun.y = mean)

library(gridExtra)
grid.arrange(p1, p2, p3, ncol = 1)
```



